In [7]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
a = np.zeros(10)

In [ ]:
a

In [ ]:
a.size

In [ ]:
a[4]=1

In [ ]:
a

In [ ]:
b = np.arange(10,50)

In [ ]:
b

In [ ]:
np.flip(b)

In [ ]:
c = x =  np.arange(2, 11).reshape(3,3)

In [ ]:
c

In [ ]:
d = ([1,2,0,0,4,0])

In [ ]:
np.nonzero(d)

In [ ]:
e = np.identity(3)

In [ ]:
e

In [ ]:
f = np.random.random((3,3,3))
f

In [ ]:
g = np.random.random((10,10))
np.min(g), np.max(g)

In [ ]:
h = np.arange(31)
h.mean()

In [11]:
i = np.ones((5,5))
i[1:-1,1:-1] = 0
i

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
j = np.ones((3,3))
j = np.pad(x, pad_width=0, mode='constant', constant_values=0)
j

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

python
0 * np.nan 
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan 
0.3 == 3 * 0.1
false

In [23]:
k = ([ 1,2,3,4,7 ])
np.diag(k)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 7]])

In [24]:
l = np.ones((3,3))
l = np.zeros((8,8),dtype=int)
l[1::2,::2] = 1
l[::2,1::2] = 1
l

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [30]:
m = np.array([0, 1, 0, 1])
np.tile(m, (8, 2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [36]:
n = np.random.random((5,5))
n

array([[0.56190524, 0.59604798, 0.68825926, 0.04689084, 0.49080291],
       [0.09848116, 0.85281125, 0.60078625, 0.94457311, 0.49739215],
       [0.65086199, 0.01866476, 0.31421389, 0.35894941, 0.44978975],
       [0.48592542, 0.29237152, 0.78683815, 0.43519799, 0.57652362],
       [0.93071996, 0.83631617, 0.26024699, 0.75229514, 0.77196119]])